<a href="https://colab.research.google.com/github/piyushyadav-art/-Machine-Learning-/blob/main/Matrix_Operation_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Matrix Addition**

In [ ]:
# creating two matrices

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [ ]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


**Adding two matrices**

In [ ]:
sum = A + B

In [ ]:
print(sum)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
# Creating the random matrix
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))
print(matrix_1)
print(matrix_2)

[[5 7 6]
 [5 6 6]
 [0 7 9]]
[[3 5 8]
 [1 6 9]
 [2 1 9]]


In [ ]:
sum = np.add(matrix_1,matrix_2)
print(sum)

[[ 8 12 14]
 [ 6 12 15]
 [ 2  8 18]]


**Matrix Substraction**

In [ ]:
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))
print(matrix_1)
print(matrix_2)

[[1 1 2]
 [6 5 4]
 [0 0 7]]
[[2 9 0]
 [4 8 7]
 [0 3 2]]


In [ ]:
sub = matrix_1 - matrix_2
print(sub)

[[-1 -8  2]
 [ 2 -3 -3]
 [ 0 -3  5]]


**Another Method of substraction**

In [ ]:
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))
print(matrix_1)
print(matrix_2)

[[9 4 4]
 [3 4 0]
 [1 5 1]]
[[0 8 7]
 [7 9 2]
 [3 8 7]]


In [ ]:
np.subtract(matrix_1,matrix_2)

array([[ 9, -4, -3],
       [-4, -5, -2],
       [-2, -3, -6]])

**Multiplication of Matrix by Scalar**

In [ ]:
x = 5
y = np.random.randint(10,size=(4,4))
print(y)

[[1 8 0 8]
 [7 5 5 3]
 [6 1 7 3]
 [2 4 2 9]]


In [ ]:
prod = np.multiply(x,y)
print(prod)

[[ 5 40  0 40]
 [35 25 25 15]
 [30  5 35 15]
 [10 20 10 45]]


**Multiply 2 matrix's**

In [ ]:
matrix_1=np.random.randint(5,size=(2,3))
matrix_2=np.random.randint(5,size=(3,3))
print(matrix_1)
print(matrix_2)

[[2 3 2]
 [4 3 0]]
[[1 2 3]
 [4 4 3]
 [1 3 4]]


In [ ]:
prod = np.dot(matrix_1,matrix_2)
print(prod)

[[16 22 23]
 [16 20 21]]


In [ ]:
matrix_1=np.random.randint(5,size=(2,2))
matrix_2=np.random.randint(5,size=(3,3))
print(matrix_1)
print(matrix_2)

[[1 3]
 [3 2]]
[[3 4 3]
 [2 1 1]
 [2 1 2]]


In [ ]:
# prod = np.dot(matrix_1,matrix_2)
# print(prod)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
# Creating two random matrix
matrix_1=np.random.randint(5,size=(2,3))
matrix_2=np.random.randint(5,size=(3,3))
print(matrix_1)
print(matrix_2)

[[1 1 1]
 [3 4 3]]
[[3 2 0]
 [1 3 2]
 [3 1 2]]


In [ ]:
prod = np.dot(matrix_1,matrix_2)
print(prod)


[[ 7  6  4]
 [22 21 14]]


Element wise matrix multiplication

In [ ]:
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,3))
print(matrix_3)
print(matrix_4)

[[3 0 0]
 [2 1 4]
 [3 0 0]]
[[0 2 3]
 [0 0 4]
 [2 1 3]]


In [ ]:
prod = np.multiply(matrix_3,matrix_4)
print(prod)#both the matrices should be same shape

[[ 0  0  0]
 [ 0  0 16]
 [ 6  0  0]]
